version: '3.7'
services:
  helix-sandbox:
    container_name: helix-sandbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
      - '443:443'
    volumes:
      - /opt/secrets/ssl_crt:/etc/nginx/certs
      - /opt/secrets/ssl_key:/etc/nginx/key
